name: Builld

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Install mojang remapped spigot jar
        run: |
            curl https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar > BuildTools.jar
            mkdir spigot
            cd spigot
            java -Xmx2G -jar BuildTools.jar --rev 1.16.5 --remapped
            java -Xmx2G -jar BuildTools.jar --rev 1.17.1 --remapped
            java -Xmx2G -jar BuildTools.jar --rev 1.18.2 --remapped
            java -Xmx2G -jar BuildTools.jar --rev 1.19.4 --remapped
            java -Xmx2G -jar BuildTools.jar --rev 1.20.4 --remapped
      - name: Build with Maven
        run: mvn clean install
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ezchestshop
          path: target/*.jar
