name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Install mojang remapped spigot jar 1.16.5 & 1.17.1
        run: |
            curl -L -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
            mkdir -p spigot
            cd spigot
            java -jar ../BuildTools.jar --rev 1.16.5 --remapped
            java -jar ../BuildTools.jar --rev 1.17.1 --remapped

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install mojang remapped spigot jar 1.18.2, 1.19.4 & 1.20.4
        run: |
            curl -L -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
            mkdir -p spigot
            cd spigot
            java -jar ../BuildTools.jar --rev 1.18.2 --remapped
            java -jar ../BuildTools.jar --rev 1.19.4 --remapped
            java -jar ../BuildTools.jar --rev 1.20.4 --remapped
      - name: Build with Maven
        run: mvn clean install
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ezchestshop
          path: target/*.jar
